### ISSUE TITLE
Doesn't works with repeatable groups

### ISSUE THREAD

**Issue by ctlcltd** [JayWood/CMB2_RGBa_Picker#2]
It doesn't works with repeatable groups, to reflect the function cmb.newRowHousekeeping() in CMB2 javascript's (that resets color pickers before to append in a new row), is required to add the html class .cmb2-colorpicker to the color picker input field.

So in jw-cmb2-rgba-colorpicker.php

``` php
echo $field_type_object->input( array(
    'class'              => 'cmb2-colorpicker color-picker', // instead color-picker only
    'data-default-color' => $field->args( 'default' ),
    'data-alpha'         => 'true'
) );
```

**Comment by JayWood** [comment]
Thanks @leolweb I've not had a need for repeatables so I would've probably never ran into this.
